DROP TABLE Order_Discount CASCADE;

DROP TABLE Pizza_Discount CASCADE;

DROP TABLE Has_Topping CASCADE;

DROP TABLE Delivery CASCADE;

DROP TABLE Pickup CASCADE;

DROP TABLE Seat_Number CASCADE;

DROP TABLE Dine_In CASCADE;

DROP TABLE Pizza CASCADE;

DROP TABLE Toppings CASCADE;

DROP TABLE Customer CASCADE;

DROP TABLE Orders CASCADE;

DROP TABLE Base_Prices CASCADE;

DROP TABLE Discounts CASCADE;
